name: movies
description: "A movie swiper"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  flutter_card_swiper: ^7.0.1
  youtube_player_flutter: ^9.0.4
  intl: ^0.19.0
  video_player: ^2.9.1
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
